version: "3.8"

services:
  backend:
    environment:
      PYTHONDONTWRITEBYTECODE: 1
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
      target: builder
    ports:
      - 3000:5173
    command: npx vite --host
    volumes:
      - ./frontend/app:/app
