version: '3.8'

services:
  mongo:
    image: mongo:4.4.18-rc0-focal
    env_file:
      - .env
    restart: always
    expose:
      - 27017
    volumes:
      - data:/data/db 

  backend:
    build: ./backend
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    volumes:
      - pictures:/app/pictures
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  data:
  pictures:
